### ISSUE TITLE
List of Countries Incomplete

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#11]
In the current .apk only Uganda, Tunisia, and Syria are available

The app should be updated with the list of countries and current contact information from the spreadsheet: https://docs.google.com/spreadsheets/d/1frBRKGuSTuTLIk3K99bqd6SbE4VpMew4gUS7m7Dvc0w/edit#gid=0

**Comment by goti921** [comment]
@AkankshaBodhankar 
I would like to contribute.

**Comment by AkankshaBodhankar** [comment]
That's great! This is an issue which requires a lot of manipulation with the database and code. You can start contributing by solving #13

**Comment by sudhachauhan** [comment]
If it's still open to be solved , I would like to take it. @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan Not right now.

**Comment by aparnavmenon** [comment]
**Description**
Data must be pulled from https://docs.google.com/spreadsheets/d/1frBRKGuSTuTLIk3K99bqd6SbE4VpMew4gUS7m7Dvc0w/edit#gid=0 and the database must be updated to reflect the latest data, regarding the list of countries and current contact information.

**Mocks**
NA

**Content**
NA

**Acceptance criteria**

- All information in the spreadsheet must be correctly reflected in the database so that the database has the latest information at all points in time.

**Comment by npari** [comment]
@MehaKaushik Is this still relevant or can this be closed?

**Comment by MehaKaushik** [comment]
No more relevant, closing it.
