### ISSUE TITLE
Installation details for Mac OS X Users

### ISSUE THREAD

**Issue by BaaniLeen** [systers/FirstAide-web#223]
@AkankshaBodhankar Can I incorporate the instructions in the Readme file about the installation of the First Aide Web App for Mac OS X users to complete the installation guidelines for Windows, Linux as well as Mac OS X? :)
Thanks..!

**Comment by MehaKaushik** [comment]
Yes, it works for me, I use Linux and I believe @AkankshaBodhankar was using windows (since she used windows styled path naming, somewhere in readme) when she created this. In my opinion, it would work for Mac OS X as well, since xampp server, google recaptcha and Twilio all are compatible with it(as a matter of fact, all of these OS are).  Try it, let us know if you face any issues.

**Comment by BaaniLeen** [comment]
Sure @MehaKaushik  :)

**Comment by MehaKaushik** [comment]
I am closing this issue now, additionally, during GSoC'17 we would be coming up with a more detailed readme, in which this too will be taken care of.
